# Generated by Django 3.2.6 on 2021-09-06 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_auto_20210906_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 6, 16, 22, 21, 193476)),
        ),
    ]
