# Generated by Django 3.2.6 on 2021-09-06 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_alter_receita_data_receita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='teste_field',
        ),
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateField(blank=True, verbose_name=datetime.datetime(2021, 9, 6, 12, 14, 40, 539417)),
        ),
    ]
